# Generated by Django 3.2.9 on 2021-11-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('thumbnail', models.CharField(max_length=248)),
                ('children', models.CharField(max_length=128)),
                ('filepath', models.CharField(max_length=248)),
            ],
        ),
        migrations.CreateModel(
            name='Subgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('thumbnail', models.CharField(max_length=248)),
                ('filepath', models.CharField(max_length=248)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('filepath', models.CharField(max_length=248)),
                ('upload_date', models.DateField()),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleries.gallery')),
                ('subgallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleries.subgallery')),
            ],
        ),
    ]
