# Generated by Django 3.2.9 on 2021-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='children',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
